// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]); 
		int big = 0;
		int small = 0; 

		while (n>0){
			double r = Math.random();
			if (r > 0.5){
				big++;
			}
			else { 
				small++;
			}
			n = n-1;
		}

		System.out.println(" > 0.5: " + big + " times");
		System.out.println(" <= 0.5: " + small + " times");


//% java TestRandom 3
//> 0.5: 3 times
//<= 0.5: 0 times
	}
}
